version: '3'

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_CONNECTION_STRING: postgres://postgres:${POSTGRES_PASSWORD}@db/postgres
      PEXELS_API_KEY: ${PEXELS_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRY_DAYS: ${JWT_EXPIRY_DAYS}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_AUDIO_BUCKET_NAME: ${S3_AUDIO_BUCKET_NAME}
      ADMIN_USER_APP_PASSWORD: ${ADMIN_USER_APP_PASSWORD}
    ports:
      - 3000:3000
    links:
      - db
