name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install and test
        run: |
          npm ci
          npm test
        env:
          CI: true

  deploy:
    needs: test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Create identity file
        env:
          DEPLOYMENTKEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$DEPLOYMENTKEY" | base64 --decode  > deployment.key
          chmod 400 deployment.key
      - name: Run deployment script on production server
        run: |
          ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i deployment.key ubuntu@snapmuse.xyz "git -C ~/snapmuse-api pull"
          ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i deployment.key ubuntu@snapmuse.xyz "~/snapmuse-api/bin/deploy.sh"
