name: CI to Docker hub

on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: docker/login-action@v1
        name: Login to DockerHub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          NODE_ENV: production
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET}}
          JWT_EXPIRY_DAYS: 30d
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_AUDIO_BUCKET_NAME: ${{ secrets.S3_AUDIO_BUCKET_NAME }}
          ADMIN_USER_APP_PASSWORD: ${{ secrets.ADMIN_USER_APP_PASSWORD }}
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/snapmuse-api:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
